2019-10-17 17:07:00.644 [pool-2-thread-1] ERROR o.s.s.support.TaskUtils$LoggingErrorHandler - Unexpected error occurred in scheduled task.
org.springframework.data.redis.RedisConnectionFailureException: Cannot get Jedis connection; nested exception is redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool
	at org.springframework.data.redis.connection.jedis.JedisConnectionFactory.fetchJedisConnector(JedisConnectionFactory.java:204)
	at org.springframework.data.redis.connection.jedis.JedisConnectionFactory.getConnection(JedisConnectionFactory.java:348)
	at org.springframework.data.redis.core.RedisConnectionUtils.doGetConnection(RedisConnectionUtils.java:129)
	at org.springframework.data.redis.core.RedisConnectionUtils.getConnection(RedisConnectionUtils.java:92)
	at org.springframework.data.redis.core.RedisConnectionUtils.getConnection(RedisConnectionUtils.java:79)
	at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:194)
	at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:169)
	at org.springframework.data.redis.core.AbstractOperations.execute(AbstractOperations.java:91)
	at org.springframework.data.redis.core.DefaultValueOperations.set(DefaultValueOperations.java:182)
	at com.zhupeng.baseframe.utils.RedisUtil.setValueAndKey(RedisUtil.java:78)
	at com.zhupeng.baseframe.task.TimerTask.timeTest(TimerTask.java:19)
	at com.zhupeng.baseframe.task.TimerTask$$FastClassBySpringCGLIB$$b5a9d8b9.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:738)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.aop.framework.adapter.MethodBeforeAdviceInterceptor.invoke(MethodBeforeAdviceInterceptor.java:52)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.adapter.AfterReturningAdviceInterceptor.invoke(AfterReturningAdviceInterceptor.java:52)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.aspectj.AspectJAfterThrowingAdvice.invoke(AspectJAfterThrowingAdvice.java:62)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:673)
	at com.zhupeng.baseframe.task.TimerTask$$EnhancerBySpringCGLIB$$b2afc8bb.timeTest(<generated>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:81)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool
	at redis.clients.util.Pool.getResource(Pool.java:53)
	at redis.clients.jedis.JedisPool.getResource(JedisPool.java:226)
	at redis.clients.jedis.JedisPool.getResource(JedisPool.java:16)
	at org.springframework.data.redis.connection.jedis.JedisConnectionFactory.fetchJedisConnector(JedisConnectionFactory.java:194)
	... 39 common frames omitted
Caused by: redis.clients.jedis.exceptions.JedisDataException: ERR Client sent AUTH, but no password is set
	at redis.clients.jedis.Protocol.processError(Protocol.java:127)
	at redis.clients.jedis.Protocol.process(Protocol.java:161)
	at redis.clients.jedis.Protocol.read(Protocol.java:215)
	at redis.clients.jedis.Connection.readProtocolWithCheckingBroken(Connection.java:340)
	at redis.clients.jedis.Connection.getStatusCodeReply(Connection.java:239)
	at redis.clients.jedis.BinaryJedis.auth(BinaryJedis.java:2139)
	at redis.clients.jedis.JedisFactory.makeObject(JedisFactory.java:108)
	at org.apache.commons.pool2.impl.GenericObjectPool.create(GenericObjectPool.java:868)
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:435)
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:363)
	at redis.clients.util.Pool.getResource(Pool.java:49)
	... 42 common frames omitted
2019-10-17 17:07:14.094 [http-nio-9999-exec-9] ERROR com.zhupeng.baseframe.exception.ExceptionHelper - null
2019-10-17 17:07:14.094 [http-nio-9999-exec-9] ERROR com.zhupeng.baseframe.exception.ExceptionHelper - null
2019-10-17 17:08:07.175 [http-nio-9999-exec-5] ERROR com.zhupeng.baseframe.exception.ExceptionHelper - null
2019-10-17 17:08:07.175 [http-nio-9999-exec-5] ERROR com.zhupeng.baseframe.exception.ExceptionHelper - null
2019-10-17 17:08:07.217 [pool-2-thread-1] ERROR o.s.s.support.TaskUtils$LoggingErrorHandler - Unexpected error occurred in scheduled task.
org.springframework.data.redis.RedisConnectionFailureException: Cannot get Jedis connection; nested exception is redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool
	at org.springframework.data.redis.connection.jedis.JedisConnectionFactory.fetchJedisConnector(JedisConnectionFactory.java:204)
	at org.springframework.data.redis.connection.jedis.JedisConnectionFactory.getConnection(JedisConnectionFactory.java:348)
	at org.springframework.data.redis.core.RedisConnectionUtils.doGetConnection(RedisConnectionUtils.java:129)
	at org.springframework.data.redis.core.RedisConnectionUtils.getConnection(RedisConnectionUtils.java:92)
	at org.springframework.data.redis.core.RedisConnectionUtils.getConnection(RedisConnectionUtils.java:79)
	at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:194)
	at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:169)
	at org.springframework.data.redis.core.AbstractOperations.execute(AbstractOperations.java:91)
	at org.springframework.data.redis.core.DefaultValueOperations.set(DefaultValueOperations.java:182)
	at com.zhupeng.baseframe.utils.RedisUtil.setValueAndKey(RedisUtil.java:78)
	at com.zhupeng.baseframe.task.TimerTask.timeTest(TimerTask.java:19)
	at com.zhupeng.baseframe.task.TimerTask$$FastClassBySpringCGLIB$$b5a9d8b9.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:738)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.aop.framework.adapter.MethodBeforeAdviceInterceptor.invoke(MethodBeforeAdviceInterceptor.java:52)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.adapter.AfterReturningAdviceInterceptor.invoke(AfterReturningAdviceInterceptor.java:52)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.aspectj.AspectJAfterThrowingAdvice.invoke(AspectJAfterThrowingAdvice.java:62)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:673)
	at com.zhupeng.baseframe.task.TimerTask$$EnhancerBySpringCGLIB$$b2afc8bb.timeTest(<generated>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:81)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool
	at redis.clients.util.Pool.getResource(Pool.java:53)
	at redis.clients.jedis.JedisPool.getResource(JedisPool.java:226)
	at redis.clients.jedis.JedisPool.getResource(JedisPool.java:16)
	at org.springframework.data.redis.connection.jedis.JedisConnectionFactory.fetchJedisConnector(JedisConnectionFactory.java:194)
	... 39 common frames omitted
Caused by: redis.clients.jedis.exceptions.JedisDataException: ERR Client sent AUTH, but no password is set
	at redis.clients.jedis.Protocol.processError(Protocol.java:127)
	at redis.clients.jedis.Protocol.process(Protocol.java:161)
	at redis.clients.jedis.Protocol.read(Protocol.java:215)
	at redis.clients.jedis.Connection.readProtocolWithCheckingBroken(Connection.java:340)
	at redis.clients.jedis.Connection.getStatusCodeReply(Connection.java:239)
	at redis.clients.jedis.BinaryJedis.auth(BinaryJedis.java:2139)
	at redis.clients.jedis.JedisFactory.makeObject(JedisFactory.java:108)
	at org.apache.commons.pool2.impl.GenericObjectPool.create(GenericObjectPool.java:868)
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:435)
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:363)
	at redis.clients.util.Pool.getResource(Pool.java:49)
	... 42 common frames omitted
2019-10-17 18:47:45.950 [http-nio-9999-exec-5] ERROR com.zhupeng.baseframe.exception.ExceptionHelper - Required request part 'file' is not present
2019-10-17 18:47:45.950 [http-nio-9999-exec-5] ERROR com.zhupeng.baseframe.exception.ExceptionHelper - Required request part 'file' is not present
2019-10-17 19:24:33.371 [http-nio-9999-exec-2] ERROR com.zhupeng.baseframe.exception.ExceptionHelper - null
2019-10-17 19:24:33.371 [http-nio-9999-exec-2] ERROR com.zhupeng.baseframe.exception.ExceptionHelper - null
2019-10-17 19:25:44.833 [http-nio-9999-exec-2] ERROR com.zhupeng.baseframe.exception.ExceptionHelper - null
2019-10-17 19:25:44.833 [http-nio-9999-exec-2] ERROR com.zhupeng.baseframe.exception.ExceptionHelper - null
2019-10-17 19:41:11.842 [http-nio-9999-exec-3] ERROR com.zhupeng.baseframe.exception.ExceptionHelper - null
2019-10-17 19:41:11.842 [http-nio-9999-exec-3] ERROR com.zhupeng.baseframe.exception.ExceptionHelper - null
2019-10-17 19:42:50.557 [http-nio-9999-exec-9] ERROR com.zhupeng.baseframe.exception.ExceptionHelper - null
2019-10-17 19:42:50.557 [http-nio-9999-exec-9] ERROR com.zhupeng.baseframe.exception.ExceptionHelper - null
2019-10-17 19:45:22.189 [http-nio-9999-exec-2] ERROR com.zhupeng.baseframe.exception.ExceptionHelper - null
2019-10-17 19:45:22.189 [http-nio-9999-exec-2] ERROR com.zhupeng.baseframe.exception.ExceptionHelper - null
2019-10-17 19:47:13.764 [http-nio-9999-exec-9] ERROR com.zhupeng.baseframe.exception.ExceptionHelper - null
2019-10-17 19:47:13.764 [http-nio-9999-exec-9] ERROR com.zhupeng.baseframe.exception.ExceptionHelper - null
2019-10-17 19:48:28.466 [http-nio-9999-exec-9] ERROR com.zhupeng.baseframe.exception.ExceptionHelper - null
2019-10-17 19:48:28.466 [http-nio-9999-exec-9] ERROR com.zhupeng.baseframe.exception.ExceptionHelper - null
2019-10-17 19:48:54.531 [http-nio-9999-exec-7] ERROR com.zhupeng.baseframe.exception.ExceptionHelper - null
2019-10-17 19:48:54.531 [http-nio-9999-exec-7] ERROR com.zhupeng.baseframe.exception.ExceptionHelper - null
2019-10-17 19:59:09.572 [http-nio-9999-exec-9] ERROR com.zhupeng.baseframe.exception.ExceptionHelper - null
2019-10-17 19:59:09.572 [http-nio-9999-exec-9] ERROR com.zhupeng.baseframe.exception.ExceptionHelper - null
2019-10-17 20:00:47.358 [http-nio-9999-exec-10] ERROR com.zhupeng.baseframe.exception.ExceptionHelper - Missing URI template variable 'deviceId2' for method parameter of type int
2019-10-17 20:00:47.358 [http-nio-9999-exec-10] ERROR com.zhupeng.baseframe.exception.ExceptionHelper - Missing URI template variable 'deviceId2' for method parameter of type int
2019-10-17 20:29:59.838 [http-nio-9999-exec-9] ERROR com.zhupeng.baseframe.exception.ExceptionHelper - null
2019-10-17 20:29:59.838 [http-nio-9999-exec-9] ERROR com.zhupeng.baseframe.exception.ExceptionHelper - null
2019-10-17 20:36:17.663 [http-nio-9999-exec-5] ERROR com.zhupeng.baseframe.exception.ExceptionHelper - null
2019-10-17 20:36:17.663 [http-nio-9999-exec-5] ERROR com.zhupeng.baseframe.exception.ExceptionHelper - null
2019-10-17 20:57:28.747 [http-nio-9999-exec-7] ERROR com.zhupeng.baseframe.exception.ExceptionHelper - null
2019-10-17 20:57:28.747 [http-nio-9999-exec-7] ERROR com.zhupeng.baseframe.exception.ExceptionHelper - null
